// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBc8VlxT-0m_AlLEWLfB2_a_IpCxAGw9w',
    appId: '1:590956477880:web:3dfb77ad4fa13a06cce34d',
    messagingSenderId: '590956477880',
    projectId: 'flutter-tutorial-feb89',
    authDomain: 'flutter-tutorial-feb89.firebaseapp.com',
    storageBucket: 'flutter-tutorial-feb89.appspot.com',
    measurementId: 'G-6QNP2R60H3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdx5c945QPWFv1r12wFL3wShJ-JgrGvIE',
    appId: '1:590956477880:android:5dc03ae019519cf8cce34d',
    messagingSenderId: '590956477880',
    projectId: 'flutter-tutorial-feb89',
    storageBucket: 'flutter-tutorial-feb89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC269lAAO1R0D54kXtrMIrsq2-mHhC8KTs',
    appId: '1:590956477880:ios:e5e12e35acddf73ccce34d',
    messagingSenderId: '590956477880',
    projectId: 'flutter-tutorial-feb89',
    storageBucket: 'flutter-tutorial-feb89.appspot.com',
    iosClientId: '590956477880-2db3bf4f3gh290e6imjvpocv4n1f2s1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC269lAAO1R0D54kXtrMIrsq2-mHhC8KTs',
    appId: '1:590956477880:ios:e5e12e35acddf73ccce34d',
    messagingSenderId: '590956477880',
    projectId: 'flutter-tutorial-feb89',
    storageBucket: 'flutter-tutorial-feb89.appspot.com',
    iosClientId: '590956477880-2db3bf4f3gh290e6imjvpocv4n1f2s1h.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTutorial',
  );
}
